from list import List

my_list = List()

my_list.insert_head_node("Matias")
my_list.insert_head_node("Alena")
my_list.insert_tail_node("Pedrito")
my_list.insert_tail_node("Juanito")
my_list.insert_node_by_position(2, "Sharon")
my_list.insert_node_by_position(5, "Emilia")
print(f"Cantidad de elementos: {my_list.list_size()}")
my_list.print_list()
my_list.delete_head_node()
print(f"Cantidad de elementos: {my_list.list_size()}")
my_list.print_list()
my_list.delete_tail_node()
print(f"Cantidad de elementos: {my_list.list_size()}")
my_list.print_list()
my_list.delete_node_by_position(3)
print(f"Cantidad de elementos: {my_list.list_size()}")
my_list.print_list()
my_list.delete_node_by_data("Sharon")
print(f"Cantidad de elementos: {my_list.list_size()}")
my_list.print_list()
